#!/usr/bin/env php

<?php

define("ROOTPATH", dirname(__FILE__) . "/../");

/**
 * Change .gitignore
 */
$gitignore = ROOTPATH . ".gitignore";
$gitignoreContents = @file_get_contents($gitignore);
$gitignoreContents = str_replace("build", "src", $gitignoreContents);
@file_put_contents($gitignore, $gitignoreContents);

/**
 * Change vercel.json
 */
$vercel = ROOTPATH . "vercel.json";
$vercelContents = @file_get_contents($vercel);
$vercelContents = str_replace("src/app.ts", "build/app.js", $vercelContents);
@file_put_contents($vercel, $vercelContents);

/**
 * Change package.json
 */
$package = ROOTPATH . "package.json";
$packageContents = @file_get_contents($package);
$packageContents = preg_replace("/\n(\s+)\"build\": \"([a-z]+)\",/", "", $packageContents);
@file_put_contents($package, $packageContents);

/**
 * Unlink tsconfig.json, nodemon.json
 * and README.md
 */
@unlink(ROOTPATH . "tsconfig.json");
@unlink(ROOTPATH . "nodemon.json");
@unlink(ROOTPATH . "README.md");

/**
 * Remove GitHub Workflows
 * and script folder
 */
@exec("rm -rf ./.github/workflows/");
@exec("rm -rf ./script/");
